export const getFirstname = (values) => values.get('firstname')
export const getLastname = (values) => values.get('lastname')
export const getUsername = (values) => values.get('username')
export const getEmail = (values) => values.get('email')
export const getTelephone = (values) => values.get('telephone')
export const getAddress = (values) => values.get('address')
export const getPassword = (values) => values.get('password')
export const getPasswordConfirmation = (values) => values.get('passwordconfirmation')
